import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Choose font weights
  variable: "--font-poppins", // Add CSS variable
});

export const metadata: Metadata = {
  title: "Fast Print",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="poppins.variable"
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
